// Placeholder catalog — will be replaced by Sanity CMS in a later stage.
// Using neutral gradient placeholders so the layout/photography drives the color.

export const products = [
  {
    id: 'p1',
    name: 'Brushed Ink Tee',
    price: 4800,
    salePrice: null,
    category: 'Tops',
    collection: 'Wear Art',
    tags: ['handpainted', 'cotton', 'unisex'],
    color: 'Charcoal',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    featured: true,
    material: '100% organic cotton',
    image: 'linear-gradient(135deg, #1a1a1a 0%, #2e2a26 100%)',
    artistNote: 'Each tee is hand-brushed with sumi ink. No two are identical.',
  },
  {
    id: 'p2',
    name: 'Acid Wash Wide Trouser',
    price: 9200,
    salePrice: 7800,
    category: 'Bottoms',
    collection: 'Limited Edition',
    tags: ['denim', 'acidwash', 'wideleg'],
    color: 'Ochre',
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
    material: 'Heavyweight denim',
    image: 'linear-gradient(135deg, #3a3226 0%, #6b5a3a 100%)',
    artistNote: 'Hand-treated acid wash, finished with raw hems.',
  },
  {
    id: 'p3',
    name: 'Mesh Veil Overshirt',
    price: 6500,
    salePrice: null,
    category: 'Outerwear',
    collection: 'Wear Art',
    tags: ['mesh', 'layering', 'artistic'],
    color: 'Black',
    sizes: ['S', 'M', 'L'],
    featured: true,
    material: 'Cotton mesh blend',
    image: 'linear-gradient(135deg, #0e0e0e 0%, #242424 100%)',
    artistNote: 'A sculptural layer, painted by hand at the seams.',
  },
  {
    id: 'p4',
    name: 'Pigment Study Hoodie',
    price: 8800,
    salePrice: null,
    category: 'Tops',
    collection: 'New Arrivals',
    tags: ['hoodie', 'pigment', 'heavyweight'],
    color: 'Slate',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    featured: false,
    material: '450gsm french terry',
    image: 'linear-gradient(135deg, #20242a 0%, #3b424a 100%)',
    artistNote: 'Pigment dyed in small batches for depth and variance.',
  },
  {
    id: 'p5',
    name: 'Canvas Cargo',
    price: 10500,
    salePrice: null,
    category: 'Bottoms',
    collection: 'New Arrivals',
    tags: ['cargo', 'canvas', 'utility'],
    color: 'Clay',
    sizes: ['S', 'M', 'L', 'XL'],
    featured: false,
    material: 'Waxed canvas',
    image: 'linear-gradient(135deg, #2c2620 0%, #574b3a 100%)',
    artistNote: 'Hand-waxed canvas that ages with the wearer.',
  },
  {
    id: 'p6',
    name: 'Stroke Knit',
    price: 7200,
    salePrice: null,
    category: 'Tops',
    collection: 'Best Sellers',
    tags: ['knit', 'wool', 'handfinished'],
    color: 'Bone',
    sizes: ['S', 'M', 'L', 'XL'],
    featured: false,
    material: 'Merino wool',
    image: 'linear-gradient(135deg, #2a2824 0%, #4a463e 100%)',
    artistNote: 'Hand-finished with a single brushstroke motif.',
  },
  {
    id: 'p7',
    name: 'Raw Edge Denim Jacket',
    price: 12500,
    salePrice: null,
    category: 'Outerwear',
    collection: 'Limited Edition',
    tags: ['denim', 'jacket', 'rawedge'],
    color: 'Indigo',
    sizes: ['S', 'M', 'L', 'XL'],
    featured: false,
    material: 'Selvedge denim',
    image: 'linear-gradient(135deg, #1c2026 0%, #2f3a4a 100%)',
    artistNote: 'Raw-edge construction, painted lining.',
  },
  {
    id: 'p8',
    name: 'Gesture Scarf',
    price: 3800,
    salePrice: null,
    category: 'Accessories',
    collection: 'Best Sellers',
    tags: ['scarf', 'silk', 'handpainted'],
    color: 'Rust',
    sizes: ['One Size'],
    featured: false,
    material: 'Hand-painted silk',
    image: 'linear-gradient(135deg, #2a201a 0%, #5a3a2a 100%)',
    artistNote: 'A single gestural painting on silk, signed by the artist.',
  },
];

export const collections = [
  { slug: 'wear-art', title: 'Wear Art', description: 'The signature line. Wearable artwork.' },
  { slug: 'limited-edition', title: 'Limited Edition', description: 'Numbered, one-time pieces.' },
  { slug: 'new-arrivals', title: 'New Arrivals', description: 'The latest from the studio.' },
  { slug: 'best-sellers', title: 'Best Sellers', description: 'Collector favourites.' },
];

export function formatINR(n) {
  return '₹' + n.toLocaleString('en-IN');
}
