name: Deploy to Netlify
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Deploy
        run: |
          npm i -g netlify-cli
          netlify deploy --dir=. --site=$NETLIFY_SITE_ID --prod --auth=$NETLIFY_AUTH_TOKEN --message="Karta home v1"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 10d14059-8b60-4d36-b982-9f9fe2683d06
